[project]
name = "wildlifecv-model"
version = "1.0.0"
description = "YOLO26 training/inference scripts for WildlifeCV project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "pytorch-triton-rocm>=3.5.1 ; sys_platform == 'linux'",
    "triton-rocm>=3.6.0 ; sys_platform == 'linux'",
    "ultralytics>=8.4.51",
    "mlflow>=3.12.0",
    "psycopg2>=2.9.12",
    "boto3>=1.43.9",
    "python-dotenv>=1.2.2"
]

[tool.uv.sources]
torch = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
torchvision = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
pytorch-triton-rocm = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
triton-rocm = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm7.2"
explicit = true

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # Pyflakes (errors)
    "UP",  # pyupgrade (modernize code for newer Python)
    "B",   # flake8-bugbear (common bugs and security issues)
    "SIM", # flake8-simplify (simplify code)
    "I",   # isort (import sorting),
    "W",
    "C901"
]
ignore = []

[tool.uv]
package = true

[project.scripts]
train-model = "runner:train"
serve-ui = "runner:serve_ui"